project:
  type: book # website # book
  output-dir: _build
  preview:
    port: 3243 # use the same port instead of a new one each time
    browser: true

# https://quarto.org/docs/books/
# https://quarto.org/docs/reference/projects/books.html
book:
  title: "Intro to Python Programming and Applications"
  author: "Michael J Rossetti"
  date: "last-modified" # "7/24/2024"
  date-format: "iso"
  #doi: "...."
  #isbn: "..."
  #issn: "..."
  #edition: "v2"

  site-url: https://prof-rossetti.github.io/intro-software-dev-python-book/
  repo-url: https://github.com/prof-rossetti/intro-software-dev-python-book/
  repo-branch: main
  repo-subdir: docs
  repo-actions: [edit, issue, source]
  #downloads: [pdf, epub, docx]

  #cover-image: images/python-banner.jpeg
  #favicon: favicon.ico

  #sharing: [twitter, facebook]

  # https://quarto.org/docs/websites/website-tools.html#open-graph
  #open-graph: true

  # https://quarto.org/docs/websites/website-tools.html#google-analytics
  # doesn't work for github pages?
  # see html: include-in-header option at bottom instead ..
  # jk use tracking id as well?
  # https://github.com/quarto-dev/quarto-cli/discussions/9065
  #google-analytics:
  #  tracking-id: "G-B1MPHWM8NN"
  # jk still doesn't work. see include-in-header option ...

  # https://quarto.org/docs/reference/projects/books.html#search
  search: #true
    location: sidebar # navbar, sidebar
    #type: textbox # overlay, textbox

  reader-mode: true

  bread-crumbs: true

  # top nav (need all these links to also be hidden chapters):
  navbar:
    right:
      - text: "Exercises"
        href: exercises/index.qmd

      - text: "Projects"
        menu:
          - exercises/rock-paper-scissors/instructions.qmd

      - about-author.qmd

  # https://quarto.org/docs/websites/website-navigation.html#side-navigation
  sidebar:
    logo: images/python-banner-2025.png


  chapters:
    - index.qmd
    - why-python.qmd

    - part: "Development Tools"
      #href:  notes/dev-tools/index.qmd
      chapters:
        - href:  notes/dev-tools/index.qmd
          text: "Development Tools Overview"
        - href: notes/dev-tools/google-colab/overview.qmd
          text: "Google Colab Notebooks"
        - notes/dev-tools/google-colab/pip.ipynb


    - "-----------------"
    - part: "Part I: Python Programming"
    - "-----------------"

    - part: "Language Basics"
      #href: notes/python-lang/overview.ipynb
      chapters:
        - href: notes/python-lang/overview.ipynb
          text: "Comments, Variables, and Built-in Functions"
        - href: notes/python-lang/python-operators.qmd
          text: "Operators"
        - href: notes/python-modules/index.qmd
          text: "Modules and Imports"

    - part: "Datatypes"
      chapters:
        - href: notes/python-lang/basic-datatypes/index.qmd
          text: "Datatypes Overview"
        # "Basic Datatypes"
        - notes/python-lang/basic-datatypes/booleans.qmd
        - notes/python-lang/basic-datatypes/numbers.qmd
        - notes/python-lang/basic-datatypes/strings.qmd
        #- "Container Datatypes"
        - notes/python-lang/container-datatypes/lists.qmd
        - notes/python-lang/container-datatypes/dictionaries.qmd

    #- part: "Basic Datatypes"
    #  chapters:
    #    - notes/python-lang/basic-datatypes/booleans.qmd
    #    - notes/python-lang/basic-datatypes/numbers.qmd
    #    - notes/python-lang/basic-datatypes/strings.qmd

    - part: "Control Flow"
      #href: notes/python-lang/control-flow/index.qmd
      chapters:
        - href: notes/python-lang/control-flow/index.qmd
          text: "Control Flow Overview"
        - notes/python-lang/control-flow/conditional-logic.qmd
        - notes/python-lang/control-flow/custom-functions.qmd
        - notes/python-lang/control-flow/errors.qmd
        - notes/python-lang/control-flow/while-loops.qmd

    #- part: "Container Datatypes"
    #  chapters:
    #    - notes/python-lang/container-datatypes/lists.qmd
    #    - notes/python-lang/container-datatypes/dictionaries.qmd

    - part: "Data Processing"
      chapters:
        - href: notes/data-processing/for-loops.qmd
          text: "List Iteration and Looping"
        - href: notes/data-processing/mapping.qmd
          text: "List Mapping"
        - href: notes/data-processing/filtering.qmd
          text: "List Filtering"
        - href: notes/data-processing/list-comprehensions.qmd
          text: "List Comprehensions"
        - href: notes/data-processing/sorting.qmd
          text: "List Sorting"


    - "-----------------"
    - part: "Part II: Python Applications"
    - "-----------------"

    - part: "Data Visualization"
      chapters:
        - href: notes/dataviz/overview.qmd
          text: "Data Visualization Overview"


    - part: "Fetching Data from the Internet"
      chapters:
        - href: notes/fetching-data/http.qmd
          text: "HTTP Requests and Responses"
        - href: notes/fetching-data/overview.qmd
          text: "Fetching Data Overview"
        - href: notes/fetching-data/json.qmd
        - href: notes/fetching-data/csv.qmd
        - href: notes/fetching-data/xml.qmd
        - href: notes/fetching-data/html-web-scraping.qmd
        - href: notes/fetching-data/automated-browsing.ipynb
          text: "Automated Browsing"
        - href: notes/fetching-data/automated-browsing-form-inputs.ipynb
          text: "Automated Browsing w/ Form Inputs"

    - part: "APIs and Integrations"
      chapters:
        - href: notes/fetching-data/apis.qmd
        - href: notes/api-integrations/youtube-audio-downloader.ipynb
          text: "YouTube Integrations"
        #- href: notes/api-integrations/sending-email-demo.ipynb
        #- href: notes/api-integrations/google-maps-api-demo.ipynb
        #- href: notes/api-integrations/spotify-api-demo.ipynb
        #- href: notes/api-integrations/pokemon-api-demo.ipynb

        #- href: notes/api-integrations/google-drive-demo.ipynb
        #- href: notes/api-integrations/google-sheets-demo.ipynb
        #- href: notes/api-integrations/openai-api-demo.ipynb
        #- href: notes/api-integrations/alphavantage-api-crypto-dashboards-demo.ipynb
        #- href: notes/api-integrations/drinks.ipynb




    - "-----------------"
    - about-author.qmd
    - "-----------------"

    - exercises/index.qmd
    - part: "Projects"
      chapters:
      - exercises/rock-paper-scissors/instructions.qmd
    - "-----------------"

  appendices:

    - part: "Google Colab In-Depth"
      chapters:
        - notes/dev-tools/google-colab/table-of-contents.qmd
        #- notes/dev-tools/google-colab/filesystem.ipynb
        - notes/dev-tools/google-colab/files.qmd
        - notes/dev-tools/google-colab/form-inputs.ipynb
        - notes/dev-tools/google-colab/notebook-secrets.qmd
        - notes/dev-tools/google-colab/advanced-integrations.ipynb

    - part: "Survey of Python Modules"
      #href: notes/python-modules/index.qmd
      chapters:
        - notes/python-modules/math.qmd
        - notes/python-modules/random.qmd
        - notes/python-modules/statistics.qmd
        - notes/python-modules/datetime.qmd
        #- notes/python-modules/getpass.ipynb

    - part: "The Programming Environment"
      #href: notes/python-modules/index.qmd
      chapters:
        - href: notes/python-modules/os.ipynb
          text: "Accessing the Filesystem with the `os` Module"
        - notes/python-lang/file-operations.qmd

    - part: "Custom Functions In-Depth"
      chapters:
        - notes/python-lang/control-flow/function-docs.qmd
        - notes/python-lang/control-flow/unit-testing.qmd

    - part: "Dataviz In-Depth"
      chapters:
        - href: notes/dataviz/trendlines.qmd
          text: "Charts with Trendlines"
        #- href: notes/dataviz/multiple-objects.qmd
        #  text: "Charts with Multiple Objects"
        - href: notes/dataviz/candlesticks.qmd
          text: "Candlestick Charts"


    #- part: "API Demos"
    #  chapters:
    #    - notes/fetching-data/apis/spotify-api-demo.ipynb
    #    - notes/fetching-data/apis/google-maps-api-demo.ipynb



  # shows up at bottom of page
  #body-footer: "&copy; Copyright 2024, Your Name Here"

  page-footer:
    center: "&copy; Copyright 2025, Michael J Rossetti"


#bibliography: references.bib

format:
  html:
    # https://quarto.org/docs/output-formats/html-themes.html
    # https://bootswatch.com/
    theme: #cosmo
      light: cosmo # default #flatly
      dark: cyborg # vapor # superhero # darkly
    css: styles/my-style.css
    code-copy: true
    #code-fold: false #show
    ##code-line-numbers: true
    #toc: true
    ##toc-depth: 3 # specify the number of section levels to include in the table of contents
    ##toc-expand: 3 # specify how much of the table of contents to show initially (defaults to 1 with auto-expansion as the user scrolls)
    #toc-expand: true # show all levels?
    ##toc-location: left
    ##number-sections: false
    ##number-depth: 1

    # https://quarto.org/docs/reference/formats/html.html#includes
    include-in-header:
      text: |
        <!-- Google tag (gtag.js) -->
        <script async src="https://www.googletagmanager.com/gtag/js?id=G-B1MPHWM8NN"></script>
        <script>
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());

          gtag('config', 'G-B1MPHWM8NN');
        </script>

  pdf:

    # use XeLaTeX or LuaLaTeX so fontspec works:
    latex-engine: xelatex

    mainfont: "Source Sans 3" # "Merriweather"
    sansfont: "Source Sans 3" # "Helvetica Neue"
    monofont: "Menlo"
    #fontsize: 11pt
    #linestretch: 1.2

    includes:
      in-header: _pdf_styles.tex

  #PrettyPDF-pdf:
  #  keep-tex: true
